name: 🤖 Android Builds
on:
  workflow_call:
    inputs:
      production:
        description: 'Enable Production build'
        default: 'false'
        type: boolean
      repo:
        description: 'Repository to use for the build'
        default: 'godotengine/godot'
        type: string
      branch:
        description: 'Branch to use for the build'
        default: 'master'
        type: string

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra werror=yes debug_symbols=no module_text_server_fb_enabled=yes strict_checks=yes swappy=yes

jobs:
  build-android:
    runs-on: ubuntu-24.04
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=editor)
            target: editor
            sconsflags: arch=arm64
# Templates
          - name: Template arm32 (target=template_release, arch=arm32)
            target: template_release_arm32
            sconsflags: arch=arm32

          - name: Template arm64 (target=template_release, arch=arm64)
            target: template_release_arm64
            sconsflags: arch=arm64
          
          - name: Template x86 (target=template_release, arch=x86)
            target: template_release_x86
            sconsflags: arch=x86
          
          - name: Template x86_64 (target=template_release, arch=x86_64)
            target: template_release_x86_64
            sconsflags: arch=x86_64

          - name: Template arm64 (target=template_debug, arch=arm64)
            target: template_debug_arm64
            sconsflags: arch=arm64
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.branch }}
          submodules: recursive

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: android-${{ matrix.target }}-${{ matrix.sconsflags }}-${{ inputs.production && 'production' || 'normal' }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Download pre-built Android Swappy Frame Pacing Library
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          repo: darksylinc/godot-swappy
          version: tags/v2023.3.0.0
          file: godot-swappy.7z
          target: swappy/godot-swappy.7z

      - name: Extract pre-built Android Swappy Frame Pacing Library
        run: 7za x -y swappy/godot-swappy.7z -o${{github.workspace}}/thirdparty/swappy-frame-pacing

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }} ${{ inputs.production && 'production=yes' || '' }}
          platform: android
          target: ${{ matrix.target }}
          scons-cache-limit: 1

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: android-${{ matrix.target }}-${{ matrix.sconsflags }}-${{ inputs.production && 'production' || 'normal' }}
        continue-on-error: true

      - name: Generate Godot templates
        if: matrix.target == 'template_release'
        run: |
          cd platform/android/java
          ./gradlew generateGodotTemplates
          cd ../../..
          ls -l bin/

      - name: Generate Godot editor
        if: matrix.target == 'editor'
        run: |
          cd platform/android/java
          ./gradlew generateGodotEditor
          ./gradlew generateGodotHorizonOSEditor
          cd ../../..
          ls -l bin/android_editor_builds/

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: android-${{ matrix.target }}-${{ matrix.sconsflags }}-${{ inputs.production && 'production' || 'normal' }}
