name: 🤖 Android Builds
on:
  workflow_call:
    inputs:
      production:
        description: 'Enable Production build'
        default: false
        type: boolean
      repo:
        description: 'Repository to use for the build'
        default: 'godotengine/godot'
        type: string
      tag:
        description: 'Branch to use for the build'
        default: 'master'
        type: string
      encryption_key:
        description: Encryption key for the build
        required: false
        type: string
        default: '7f5ddb606888db9a20dbf00b76f9b426f81e48d299c7093d5119b39967bae8f1'
      build_profile:
        description: 'Build profile file path.'
        required: false
        type: string
        default: ''
      module_flags:
        description: 'Extra module flags, e.g. module_webm_enabled=no'
        required: false
        type: string
        default: ''

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: 4.4
  SCONSFLAGS: verbose=yes warnings=extra werror=yes debug_symbols=no module_text_server_fb_enabled=yes strict_checks=yes swappy=yes ${{ inputs.module_flags }} build_profile=${{ inputs.build_profile }}
  SCRIPT_AES256_ENCRYPTION_KEY: ${{ inputs.encryption_key }}

jobs:
  build-android:
    runs-on: ubuntu-24.04
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
# Templates
          - name: Template arm32 (target=template_release, arch=arm32)
            target: template_release
            sconsflags: arch=arm32

          - name: Template arm64 (target=template_release, arch=arm64)
            target: template_release
            sconsflags: arch=arm64
          
          - name: Template x86 (target=template_release, arch=x86)
            target: template_release
            sconsflags: arch=x86
          
          - name: Template x86_64 (target=template_release, arch=x86_64)
            target: template_release
            sconsflags: arch=x86_64

          - name: Template arm64 (target=template_debug, arch=arm64)
            target: template_debug
            sconsflags: arch=arm64
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.tag }}
          submodules: recursive

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: android-${{ matrix.target }}-${{ matrix.sconsflags }}-${{ inputs.production && 'production' || 'normal' }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Download pre-built Android Swappy Frame Pacing Library
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          repo: godotengine/godot-swappy
          version: tags/from-source-2025-01-31
          file: godot-swappy.7z
          target: swappy/godot-swappy.7z

      - name: Extract pre-built Android Swappy Frame Pacing Library
        run: 7za x -y swappy/godot-swappy.7z -o${{github.workspace}}/thirdparty/swappy-frame-pacing

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }} ${{ inputs.production && 'production=yes' || '' }}
          platform: android
          target: ${{ matrix.target }}
          scons-cache-limit: 1

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: android-${{ matrix.target }}-${{ matrix.sconsflags }}-${{ inputs.production && 'production' || 'normal' }}
        continue-on-error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-${{ matrix.target }}-${{ matrix.sconsflags }}-${{ inputs.production && 'production' || 'normal' }}
          path: bin
