name: 🚀 Create Release
on:
  workflow_call:
    inputs:
      production:
        description: 'Enable Production build'
        default: false
        type: boolean
      repo:
        description: 'Repository to use for the build'
        default: 'godotengine/godot'
        type: string
      tag:
        description: 'Branch to use for the build'
        default: 'master'
        type: string
      encryption_key:
        description: Encryption key for the build
        required: false
        type: string
        default: '7f5ddb606888db9a20dbf00b76f9b426f81e48d299c7093d5119b39967bae8f1'
      build_profile:
        description: 'Build profile file path.'
        required: false
        type: string
        default: ''
      module_flags:
        description: 'Extra module flags, e.g. module_webm_enabled=no'
        required: false
        type: string
        default: ''

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: 4.4
  SCONSFLAGS: verbose=yes warnings=extra werror=yes strict_checks=yes debug_symbols=no ${{ inputs.module_flags }} build_profile=${{ inputs.build_profile }}
  SCRIPT_AES256_ENCRYPTION_KEY: ${{ inputs.encryption_key }}

jobs:
  release:
    name: 🚀 Create Release
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.tag }}
          submodules: recursive

      - uses: actions/download-artifact@v4
        with:
          path: bin
          merge-multiple: true

      - name: List downloaded bin
        run: ls -R bin
      
      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Checkout script repo for install_vulkan_sdk_macos.sh
        uses: actions/checkout@v4
        with:
          repository: appsinacup/action_godot_builder
          path: misc/scripts

      - name: Setup Vulkan SDK
        run: |
          sh misc/scripts/install_vulkan_sdk_macos.sh

      - name: Mac Create Editor Bundle
        run: |
          cp -r misc/dist/macos_tools.app ./bin/Godot.app
          mkdir -p bin/Godot.app/Contents/MacOS
          cp bin/godot.macos.editor.universal bin/Godot.app/Contents/MacOS/Godot
          chmod +x bin/Godot.app/Contents/MacOS/Godot
          codesign --force --timestamp --options=runtime --entitlements misc/dist/macos/editor.entitlements -s - bin/Godot.app

      - name: Mac Create Template Bundle
        run: |

          cp -r misc/dist/macos_template.app ./bin
          mkdir -p bin/macos_template.app/Contents/MacOS
          cp bin/godot.macos.template_release.universal bin/macos_template.app/Contents/MacOS/godot_macos_release.universal
          cp bin/godot.macos.template_debug.universal bin/macos_template.app/Contents/MacOS/godot_macos_debug.universal
          chmod +x bin/macos_template.app/Contents/MacOS/godot_macos*
          zip -q -9 -r bin/macos.zip bin/macos_template.app
      
      - name: Android Generate Godot templates
        run: |
          cd platform/android/java
          ./gradlew generateGodotTemplates
          cd ../../..
          ls -l bin/

      - name: Package per-platform editors and templates
        run: |
          set -e
          VERSION=${{ inputs.tag }}
          VERSION_CLEAN=${VERSION//-/.}
          mkdir -p release/templates/$VERSION_CLEAN

          # Editors
          cp bin/godot.linuxbsd.editor.x86_64* release/Godot_v${VERSION_CLEAN}_linux.x86_64.zip || exit
          cp bin/godot.linuxbsd.editor.x86* release/Godot_v${VERSION_CLEAN}_linux.x86_32.zip || exit
          cp bin/godot.windows.editor.x86_64* release/Godot_v${VERSION_CLEAN}_win64.exe.zip || exit
          cp bin/godot.windows.editor.x86* release/Godot_v${VERSION_CLEAN}_win32.exe.zip || exit
          cp bin/godot.windows.editor.arm64* release/Godot_v${VERSION_CLEAN}_windows_arm64.exe.zip || exit
          cp bin/godot.macos.editor.universal* release/Godot_v${VERSION_CLEAN}_macos.universal.zip || exit
          cp bin/Godot.app.zip release/Godot_v${VERSION_CLEAN}_macos.app.zip || exit

          # Export templates
          cp bin/godot.linuxbsd.template_release.x86_64* release/templates/$VERSION_CLEAN/linux_x86_64_release.zip || exit
          cp bin/godot.linuxbsd.template_release.x86* release/templates/$VERSION_CLEAN/linux_x86_32_release.zip || exit
          cp bin/godot.windows.template_release.x86_64* release/templates/$VERSION_CLEAN/windows_x86_64_release.zip || exit
          cp bin/godot.windows.template_release.x86* release/templates/$VERSION_CLEAN/windows_x86_32_release.zip || exit
          cp bin/godot.windows.template_release.arm64* release/templates/$VERSION_CLEAN/windows_arm64_release.zip || exit
          cp bin/godot.macos.template_release.universal* release/templates/$VERSION_CLEAN/macos_universal_release.zip || exit
          cp bin/macos.zip release/templates/$VERSION_CLEAN/macos_bundle.zip || exit
          cp bin/godot.web.template_release* release/templates/$VERSION_CLEAN/web_release.zip || exit
          # Add Android/iOS templates as needed

          # Create export templates .tpz
          cd release
          zip -r Godot_v${VERSION_CLEAN}_export_templates.tpz templates
      
      - name: List release directory
        run: ls -R release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Custom Godot Release ${{ github.ref_name }}"
          files: |
            release/Godot_v${{ inputs.tag }}_linux.x86_64.zip
            release/Godot_v${{ inputs.tag }}_linux.x86_32.zip
            #release/Godot_v${{ inputs.tag }}_linux.arm64.zip
            #release/Godot_v${{ inputs.tag }}_linux.arm32.zip
            release/Godot_v${{ inputs.tag }}_win64.exe.zip
            release/Godot_v${{ inputs.tag }}_win32.exe.zip
            release/Godot_v${{ inputs.tag }}_windows_arm64.exe.zip
            release/Godot_v${{ inputs.tag }}_macos.universal.zip
            release/Godot_v${{ inputs.tag }}_macos.app.zip
            release/Godot_v${{ inputs.tag }}_web_editor.zip
            release/Godot_v${{ inputs.tag }}_android_editor.aab
            release/Godot_v${{ inputs.tag }}_android_editor.apk
            release/Godot_v${{ inputs.tag }}_android_editor_horizonos.apk
            release/Godot_v${{ inputs.tag }}_android_editor_picoos.apk
            release/Godot_v${{ inputs.tag }}_ios_editor.zip
            release/Godot_v${{ inputs.tag }}_export_templates.tpz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
